[tool.poetry]
name = "clmac"
version = "0.1.0"
description = ""
authors = ["Alexander Lewzey <a.lewzey@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pynput = "^1.7.6"
pyperclip = "^1.8.2"
textblob = "^0.18.0.post0"
pytesseract = "^0.3.10"
numpy = "^1.26.4"
opencv-python = "^4.9.0.80"
pillow = "^10.3.0"
pyttsx3 = "^2.90"
autoflake = "^2.3.1"
sqlfluff = "^3.0.5"
black = "^24.4.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
mypy = "^1.10.0"
pre-commit = "^3.7.0"
isort = "^5.13.2"
flake8 = "^7.0.0"
jupyter = "^1.0.0"
docformatter = "^1.7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
clmac = "clmac.app:run"
