[tool.poetry]
name = "clmac"
version = "0.1.0"
description = ""
authors = ["Alexander Lewzey <a.lewzey@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pynput = "^1.7.6"
pyperclip = "^1.8.2"
textblob = "^0.17.1"
pytesseract = "^0.3.10"
numpy = "^1.24.3"
opencv-python = "^4.7.0.72"
pillow = "^9.5.0"
pyttsx3 = "^2.90"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
