name: Code Quality

on:
  push:
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install poetry and dependencies
      run: |
        pip install poetry
        poetry install --no-interaction --no-ansi

    - name: Run pre-commit and check for changes
      id: check_changes
      run: |
        SKIP=test poetry run pre-commit run --all-files
