name: Format code
on:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install pre-commit
      run: pip install pre-commit pytest
    - name: Run pre-commit on all files
      run: pre-commit run --all-files
    - name: Check for changes
      id: step1
      run: |
        if git diff --exit-code; then
          echo "run_commit_changes=false" >> $GITHUB_OUTPUT
          echo "No changes made by formatters. Skipping commit and push."
        else
          echo "run_commit_changes=true" >> $GITHUB_OUTPUT
          echo "Changes made by formatters. Executing commit and push."
        fi
    - name: Commit changes
      if: steps.step1.outputs.run_commit_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Format code with black isort docformatter autoflake"
        git push
