name: Format code

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format code with Black and isort
        run: |
          black .
          isort .

      - name: Check for changes
        run: |
          if [git diff --exit-code]; then
            echo "export COMMIT_CHANGES=false" >> $GITHUB_ENV
            echo "No changes made by Black and isort. Skipping commit and push."
          else
              echo "export COMMIT_CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: $COMMIT_CHANGES == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Format code with Black and isort"
          git push
          