name: Format code

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format code with Black and isort
        run: |
          black .
          isort .

      - name: Check for changes
        id: step1
        run: |
          if git diff --exit-code; then
            run: echo "::set-output name=my_output::false"
            echo "No changes made by Black and isort. Skipping commit and push."
          else
            run: echo "::set-output name=my_output::true"
          fi

      - name: Commit changes
        if: steps.step1.outputs.my_output == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Format code with Black and isort"
          git push
