name: Format code

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format code with Black and isort
        run: |
          black .
          isort .

      - id: s1
      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "No changes made by Black and isort. Skipping commit and push."
            exit 0
          fi

      - name: Commit changes
        if: steps.s1.conclusion == 'failure'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Format code with Black and isort"
          git push